# GitHub Pages Configuration for AF_PROOF
theme: jekyll-theme-hacker
title: "AF_PROOF: Operation Untouchable Evidence Repository"
description: "When solicitors become cybercriminals, Blackwood delivers justice"
show_downloads: false

# Navigation
nav:
  - title: "Timeline"
    url: "/timeline/"
  - title: "Evidence"
    url: "/evidence/"
  - title: "Legal"
    url: "/legal/"

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from build
exclude:
  - scripts/
  - DEPLOYMENT_PLAN.md
  - LICENSE
  - .gitignore